version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.7
    steps:
      - checkout
      - run: go mod download
      - run: go test -v ./...

workflows:
  version: 2
  test:
    jobs:
      - test
